### ISSUE TITLE
question about run code and your sample data 

### ISSUE THREAD

**Issue by lixuliang** [nguyend/congestionpropagation#1]
Hello, I'm having problems running your code and sample data. I haven't made any importance changes to the code. I hope that I can have your advice.

One of the only changes was "Exception," which was changed to "Exception as". One is the "len(map)" changed to "list(map)". It seems that this is because of the adjustment of the map object.

There will be two errors now. I have no idea at all. In the first error, I got "float division by zero". My query seems to be because that "dataset" is empty in apriori.py, this problem does not always appear.
The second case always appears. result of the code line "Frequents, support = apriori (alltrees, 0.01)" are both empty, always!

I'm sure that I haven't changed anywhere else in the code or data, so I'm in big troubled as an novice student. Hope to get your help, thanks a lot!

**Comment by nguyend** [comment]
I have uploaded the gmploy.py which is modified for the map object.
You can try again by replacing the same file in the site-packages library by this customized file.
I used Python 2.7 and the output should be (segments in the tree and the frequent):
causaltree.py
([514, 550, 521, 522, 527, 276], 4.0)
([578, 389, 400, 537, 538, 542], 19.0)
([578, 389, 537, 538, 411, 542], 9.0)
([578, 389, 400, 538, 411, 542], 9.0)
([448, 515, 521, 524, 526, 532], 5.0)
([578, 400, 537, 538, 411, 542], 9.0)
([578, 389, 400, 537, 411, 542], 9.0)
([448, 515, 487, 530, 532, 446], 6.0)
([389, 400, 537, 538, 411, 542], 9.0)
([578, 389, 400, 537, 538, 411], 9.0)
([389, 557, 400, 538, 411, 542], 4.0)
([489, 428, 494, 471, 474, 477], 4.0)
([451, 453, 456, 555, 118, 122], 6.0)
([452, 454, 455, 556, 120, 121], 4.0)
([578, 389, 400, 537, 538, 411, 542], 9.0)
(578, 578)
(578, 389)
(578, 400)
(578, 537)
(578, 538)
(578, 542)
(389, 578)
(389, 389)
(389, 400)
(389, 537)
(389, 538)
(389, 542)
(400, 578)
(400, 389)
(400, 400)
(400, 537)
(400, 538)
(400, 542)
(537, 578)
(537, 389)
(537, 400)
(537, 537)
(537, 538)
(537, 542)
(538, 578)
(538, 389)
(538, 400)
(538, 537)
(538, 538)
(538, 542)
(542, 578)
(542, 389)
(542, 400)
(542, 537)
(542, 538)
(542, 542)
[(578, 537), (400, 389), (537, 538), (538, 542), (542, 400)]
(0.0, 0.05477860619471668)

Process finished with exit code 0

**Comment by lixuliang** [comment]
Thanks for your very quick answer, thank you very much. I will try to use python2.7 to try the updated code. Thanks
