### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jinyuanliu23** [nguyend/congestionpropagation#2]
![image](https://user-images.githubusercontent.com/63135879/88768241-5ee78500-d1ad-11ea-84e3-fde96f55376c.png)
how to deal with this issue? maybe lack of some packages,can you give me a hand?

**Comment by nguyend** [comment]
Which python version are you using? I used Python 2.7, I haven't got this
error before.

**Comment by jinyuanliu23** [comment]
![image](https://user-images.githubusercontent.com/63135879/89184424-5aff9c80-d5cb-11ea-958f-c3666fc9e4a4.png)
what are the parent packages of ".color_dicts"?  i used Python 3.7 before. Now ,i use Python 2.7.17.But ,the problem still persists.Seems not just a matter of version.

**Comment by jinyuanliu23** [comment]
[image: image.png]
Professor Nguyen,
  dear what are the parent packages of ".color_dicts"? i used Python 3.7
before. Now ,i use Python 2.7.17.But ,the problem still persists.Seems not
just a matter of version.Can you give me more information?

nguyend <notifications@github.com> 于2020年7月29日周三 下午5:26写道：

**Comment by nguyend** [comment]
This could be gmplot version (which is not developed by me).
Have you tried different version of gmplot (e.g. 1.1.0)?
If the import error is still there you may need to contact the gmplot
author directly.
Regards,
Hoang Nguyen
